//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3082
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("uNhAddIns")]
[assembly: AssemblyCopyright("Copyright (c) uNhAddIns, 2008. All rights reserved.")]
[assembly: AssemblyProduct("uNhAddIns.ComponentBehaviors.Castle")]
[assembly: AssemblyTitle("uNhAddIns.ComponentBehaviors.Castle")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("2.0.0.797")]
[assembly: AssemblyVersion("2.0.0.797")]


