//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("uNhAddIns")]
[assembly: AssemblyCopyright("Copyright (c) uNhAddIns, 2008. All rights reserved.")]
[assembly: AssemblyProduct("uNhAddIns.ComponentBehaviors.Castle")]
[assembly: AssemblyTitle("uNhAddIns.ComponentBehaviors.Castle")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyInformationalVersion("2.0.0.788")]
[assembly: AssemblyVersion("2.0.0.788")]


