namespace GoldParsing.Engine
{
	/// <summary>
	/// This is a visitor-interface for the parse tree generated by GoldParser.
	/// See the sample project for more information.
	/// </summary>
	public interface IVisitor
	{
		void Visit(Reduction reduction);
	}
}