//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3082
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly : AssemblyCompany("uNhAddIns")]
[assembly : AssemblyCopyright("Copyright (c) uNhAddIns, 2008. All rights reserved.")]
[assembly : AssemblyProduct("uNhAddIns.WPF.Castle")]
[assembly : AssemblyTitle("uNhAddIns.WPF.Castle")]
[assembly : CLSCompliant(true)]
[assembly : AssemblyInformationalVersion("2.0.0.720")]
[assembly : AssemblyVersion("2.0.0.720")]