using System;
using Antlr.Runtime;
using Antlr.Runtime.Tree;

namespace NHibernate.Hql.Ast.ANTLR.Tree
{
	/// <summary>
	/// A select expression that was generated by a FROM element.
	/// Author: josh
	/// Ported by: Steve Strong
	/// </summary>
	public class SelectExpressionImpl :FromReferenceNode, ISelectExpression 
	{
		public SelectExpressionImpl(IToken token) : base(token)
		{
		}

		public override void ResolveIndex(ITree parent)
		{
			throw new InvalidOperationException();
		}

		public override void SetScalarColumnText(int i)
		{
			String text = FromElement.RenderScalarIdentifierSelect( i );
			SetText( text );
		}

		public override void Resolve(bool generateJoin, bool implicitJoin, string classAlias, ITree parent)
		{
			// Generated select expressions are already resolved, nothing to do.
			return;
		}
	}
}
